import Head from 'next/head'
import { useState } from "react";

import { useRouter } from 'next/navigation';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import HeroImage from '@/components/HeroImage'
import {
  Stack,
  Flex,
  Button,
  Text,
  VStack,
  useBreakpointValue,
  InputGroup,
  Input,
  InputRightElement,
  HStack,
  Container,
  Box
} from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const [query, setQuery] = useState("");

  const searchMovie = () =>{
    if(query.trim() !== ""){
      router.push(`/result/${query}`)
    }
  }

  return (
    <>
      <Head>
        <title>Cinemarker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroImage>
          <VStack w={'full'}  px={useBreakpointValue({ base: 4, md: 8 })} py={"10em"}>
            <Stack maxW={'2xl'} align={'flex-start'} spacing={6}>
              <Flex alignItems={'center'} justifyContent={'space-between'}>
                <svg style={{color: 'white', fontWeight: '600'}} xmlns="http://www.w3.org/2000/svg" width={useBreakpointValue({ base: "70", md: "100" })} height={useBreakpointValue({ base: "70", md: "100" })} fill="currentColor" className="bi bi-film" viewBox="0 0 16 16"> <path d="M0 1a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm4 0v6h8V1H4zm8 8H4v6h8V9zM1 1v2h2V1H1zm2 3H1v2h2V4zM1 7v2h2V7H1zm2 3H1v2h2v-2zm-2 3v2h2v-2H1zM15 1h-2v2h2V1zm-2 3v2h2V4h-2zm2 3h-2v2h2V7zm-2 3v2h2v-2h-2zm2 3h-2v2h2v-2z" fill="white"></path> </svg>
                <div style={{width: "0.5em"}}></div>
                <Text color={'white'} fontWeight={700} lineHeight={1.2} fontSize={useBreakpointValue({ base: '4xl', md: '5xl' })}>
                  Cinemarker
                </Text>
              </Flex>
            </Stack>

            <HStack w={useBreakpointValue({ base: "90%", md: "55%" })} py={"2em"}>
              <InputGroup size='lg'>
                <Input
                  type='text'
                  placeholder='Search movie title'
                  background={"white"}
                  w={"full"}
                  onChange={(e) => setQuery(e.target.value)}
                  onKeyPress={e=> {
                    if (e.key === 'Enter') {
                      searchMovie()
                    }
                 }}
                />
                <InputRightElement width='4rem'>
                  <Button h='full' size='sm' background={"#A52A2A"} color={"white"} _hover={{background: "#420D09"}} onClick={searchMovie}>
                    search
                  </Button>
                </InputRightElement>
              </InputGroup>
            </HStack>

            <Container maxW='4xl' centerContent>
              <Box padding='4' color='white' maxW='2xl'>
                <Text fontSize={useBreakpointValue({ base: 'md', md: 'md' })}>
                Can't remember what movie you want to watch Friday night? <b>Cinemarker</b> is an application that allows user to search for movie by title and bookmark them.
                Once bookmarked, the user can view, review, marked as watched, and remove the movie from the bookmark list. 
                </Text>
              </Box>
          </Container>
        </VStack>      
      </HeroImage>
    </>
  )
}

// export const getStaticProps = async () => {

// }